NUM_ACTIONS = 3
LEARNING_RATE = 1e-3
GAMMA = 0.99
N_STEP_RETURN = 10
GAMMA_N = GAMMA ** N_STEP_RETURN

LOSS_V = .5
LOSS_ENTROPY = 0.01

RMS_DECAY = 0.8

MEMORY_SIZE = 5
NUM_STATE = 20 * MEMORY_SIZE

NUM_ANTS = 25
DECAY_RATE = 0.998 # decay rate of pheromones
EPSILON_START = 0.99
EPSILON_END = 0.2
EPSILON_STEPS = 1e+4
